package main.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class GameTest {
  private WebDriver driver;
  private WebDriverWait wait;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void game() {
    driver.get("https://s0urce.io/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.name("input")).click();
    driver.findElement(By.name("input")).sendKeys("test");
    wait.until(
            ExpectedConditions.elementToBeClickable(By.cssSelector(".grey"))
    );
    driver.findElement(By.cssSelector(".grey")).click();
    wait.until(
            ExpectedConditions.elementToBeClickable(By.cssSelector("div:nth-child(17) > .wrapper"))
    );
    driver.findElement(By.cssSelector("div:nth-child(17) > .wrapper")).click();
    driver.findElement(By.name("input")).click();
    driver.findElement(By.name("input")).sendKeys("TV");
    driver.findElement(By.cssSelector(".country-entry:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".element > div > div:nth-child(2)"));
      System.out.println(element.getText());
      assertEquals("TV • Tuvalu", element.getText());
    }
  }
}
