package main.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class RandomTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void randomTest() {
    driver.get("https://www.calculator.net/random-number-generator.html");
    driver.manage().window().setSize(new Dimension(550, 692));
    driver.findElement(By.name("x")).click();
    driver.findElement(By.id("contentout")).click();
    driver.findElement(By.cssSelector(".verybigtext")).click();
    assertTrue(driver.findElement(By.cssSelector(".verybigtext")).getText().matches("^[0-9]+$"));
    {
      WebElement element = driver.findElement(By.cssSelector(".verybigtext"));
      String text = element.getText();
      int number = Integer.parseInt(text);

      System.out.println(text);

      assertTrue(text.matches("^[0-9]+$"));
      assertTrue(number >= 1);
      assertTrue(number <= 100);
    }
  }
}
